import type { MetadataRoute } from "next";
import { siteConfig } from "@/lib/site-config";

/**
 * Web manifest for PWA installability and Android home-screen icons.
 * Icons reference the Next.js file-based conventions: `/icon.svg`
 * (static SVG file), `/icon` (PNG generated by `icon.tsx`), and
 * `/apple-icon` (PNG generated by `apple-icon.tsx`). Next.js routes
 * these without extensions — the content-type header carries the
 * format.
 *
 * `theme_color` matches Claude orange so the address-bar tint on
 * Android installs reads as the brand. `background_color` is
 * Anthropic ivory so the splash screen is consistent with the rest
 * of the site.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: siteConfig.name,
    short_name: siteConfig.name,
    description: siteConfig.description,
    start_url: "/",
    display: "standalone",
    background_color: "#faf9f5",
    theme_color: "#d97757",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icon",
        sizes: "32x32",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
